apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web.labels" . | nindent 8 }}
    spec:
      {{- with .Values.web.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.web.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          command: ["nginx", "-g", "daemon off;"]
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: port1
              containerPort: {{ .Values.web.service.ports.port1.containerPort }}
              protocol: {{ .Values.web.service.ports.port1.protocol }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d
            - name: logs-volume
              mountPath: /var/log/nginx
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          env:
            - name: DASHBOARD_HOST_NAME
              value: {{ include "api.fullname" . }}
            - name: DASHBOARD_HOST_PORT
              value: "{{ .Values.api.service.ports.port1.containerPort }}"
            - name: ENABLE_AUTH_IDM
              value: "{{ .Values.enableAuthIdm }}"
            - name: CAR_INDEX
              value: "{{ .Values.web.envVars.CAR_INDEX }}"              
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "web.fullname" . }}-configmap
        - name: logs-volume
          emptyDir: {}

